// Code generated by protoc-gen-go.
// source: pkg/crowdsound/crowdsound_admin_service.proto
// DO NOT EDIT!

package crowdsound

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SkipStatusRequest struct {
}

func (m *SkipStatusRequest) Reset()                    { *m = SkipStatusRequest{} }
func (m *SkipStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*SkipStatusRequest) ProtoMessage()               {}
func (*SkipStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type SkipStatusResponse struct {
	VotesToSkip int32 `protobuf:"varint,1,opt,name=votes_to_skip" json:"votes_to_skip,omitempty"`
	TotalUsers  int32 `protobuf:"varint,2,opt,name=total_users" json:"total_users,omitempty"`
}

func (m *SkipStatusResponse) Reset()                    { *m = SkipStatusResponse{} }
func (m *SkipStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*SkipStatusResponse) ProtoMessage()               {}
func (*SkipStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type SkipRequest struct {
}

func (m *SkipRequest) Reset()                    { *m = SkipRequest{} }
func (m *SkipRequest) String() string            { return proto.CompactTextString(m) }
func (*SkipRequest) ProtoMessage()               {}
func (*SkipRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type SkipResponse struct {
}

func (m *SkipResponse) Reset()                    { *m = SkipResponse{} }
func (m *SkipResponse) String() string            { return proto.CompactTextString(m) }
func (*SkipResponse) ProtoMessage()               {}
func (*SkipResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func init() {
	proto.RegisterType((*SkipStatusRequest)(nil), "CrowdSound.SkipStatusRequest")
	proto.RegisterType((*SkipStatusResponse)(nil), "CrowdSound.SkipStatusResponse")
	proto.RegisterType((*SkipRequest)(nil), "CrowdSound.SkipRequest")
	proto.RegisterType((*SkipResponse)(nil), "CrowdSound.SkipResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Admin service

type AdminClient interface {
	SkipStatus(ctx context.Context, in *SkipStatusRequest, opts ...grpc.CallOption) (*SkipStatusResponse, error)
	Skip(ctx context.Context, in *SkipRequest, opts ...grpc.CallOption) (*SkipResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) SkipStatus(ctx context.Context, in *SkipStatusRequest, opts ...grpc.CallOption) (*SkipStatusResponse, error) {
	out := new(SkipStatusResponse)
	err := grpc.Invoke(ctx, "/CrowdSound.Admin/SkipStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) Skip(ctx context.Context, in *SkipRequest, opts ...grpc.CallOption) (*SkipResponse, error) {
	out := new(SkipResponse)
	err := grpc.Invoke(ctx, "/CrowdSound.Admin/Skip", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Admin service

type AdminServer interface {
	SkipStatus(context.Context, *SkipStatusRequest) (*SkipStatusResponse, error)
	Skip(context.Context, *SkipRequest) (*SkipResponse, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_SkipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SkipStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AdminServer).SkipStatus(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Admin_Skip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(SkipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AdminServer).Skip(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CrowdSound.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SkipStatus",
			Handler:    _Admin_SkipStatus_Handler,
		},
		{
			MethodName: "Skip",
			Handler:    _Admin_Skip_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor1 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x2d, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2e, 0xca, 0x2f, 0x4f, 0x29, 0xce, 0x2f, 0xcd, 0x4b, 0x41, 0x62, 0xc6, 0x27, 0xa6, 0xe4,
	0x66, 0xe6, 0xc5, 0x17, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4,
	0x0b, 0x71, 0x39, 0x83, 0xe4, 0x83, 0x41, 0xf2, 0x4a, 0xc2, 0x5c, 0x82, 0xc1, 0xd9, 0x99, 0x05,
	0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0x0e, 0x5c,
	0x42, 0xc8, 0x82, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xa2, 0x5c, 0xbc, 0x65, 0xf9, 0x25,
	0xa9, 0xc5, 0xf1, 0x25, 0xf9, 0xf1, 0xc5, 0x40, 0x69, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x56, 0x21,
	0x61, 0x2e, 0xee, 0x92, 0xfc, 0x92, 0xc4, 0x9c, 0xf8, 0x52, 0xa0, 0x2d, 0xc5, 0x12, 0x4c, 0x20,
	0x41, 0x25, 0x5e, 0x2e, 0x6e, 0x90, 0x09, 0x30, 0x03, 0xf9, 0xb8, 0x78, 0x20, 0x5c, 0x88, 0x51,
	0x46, 0x93, 0x19, 0xb9, 0x58, 0x1d, 0x41, 0x2e, 0x13, 0xf2, 0xe5, 0xe2, 0x42, 0x58, 0x25, 0x24,
	0xab, 0x87, 0x70, 0x9a, 0x1e, 0x86, 0xbb, 0xa4, 0xe4, 0x70, 0x49, 0x43, 0x8c, 0x55, 0x62, 0x10,
	0xb2, 0xe6, 0x62, 0x01, 0x89, 0x0b, 0x89, 0xa3, 0xab, 0x84, 0x19, 0x21, 0x81, 0x29, 0x01, 0xd3,
	0xec, 0xc4, 0x13, 0xc5, 0x85, 0x08, 0xb9, 0x24, 0x36, 0x70, 0x60, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0x7a, 0x3e, 0xa7, 0x5d, 0x01, 0x00, 0x00,
}
